### PR TITLE
Inital push of InfluxDB integration

### PR DESCRIPTION
**Pull request by ehsanmasdar**

### CODE REVIEW

**Comment by ehsanmasdar** [comment]
@petschekr I need some help verifying if this actually works and if I inserted the metrics code in the right place. I haven't actually seen this work end to end locally and I'm having trouble figuring out what I'm doing wrong to get the code to branch in that path

**Comment by illegalprime** [comment]
looks cool, what about using the stdout of a process?

**Comment by ehsanmasdar** [comment]
@illegalprime This is fundamentally accomplishing a different goal. More visualization of app-specific metrics rather than searchable logging. Elasticsearch is way overkill

**Comment by illegalprime** [comment]
@ehsanmasdar I'd like all our apps to feed into grafana, or some other vis, is that reasonable and is there a way to do it?

**Pull request closed without merging**
