### PR TITLE
Implement an RSVP stage with email content customization

### LINKED ISSUE #49: Accepted RSVP / question form
Accessed after being accepted to confirm attending the event

Blocked by #48

### PR DESCRIPTION
**Pull request by petschekr**
This PR adds an RSVP stage for users who have been accepted by admins (known as the confirmation stage). Additional question branches can be added to the `questions.json` and can be selected as "Application", "Confirmation", and "No-op" respectively. Confirmation works similarly to the initial application in most other regards.

Another major feature added is the ability to customize the email content sent by the applications post-apply, post-confirm, and post-acceptance. This happens in the Settings section of the admin panel. Emails are composed in Markdown / HTML with an embedded richtext editor and live preview of both the rendered HTML and text content. Variable interpolation for variables like the event name, user information, and limited application data is also supported.

Finally, adding to #60, emails are now sent when users have been accepted from the admin panel and the Send Acceptance Emails button is clicked. Acceptance emails will only be sent once per user -- even if they are un-accepted and accepted again.

Closes #49 and completes the email content portion of #38

### CODE REVIEW

**Comment by ehsanmasdar** [comment]
@petschekr Seems sane from what I read. Is there a particular section you want me to really look at? Otherwise I would just probably smoke test and call it good.

**Comment by petschekr** [comment]
@ehsanmasdar Nothing really in particular. I submitted this after several late nights of work so I just wanted to make sure that this huge PR works on other machines too and that there aren't any particularly obvious bugs or code smells.

**Comment by ehsanmasdar** [comment]
@petschekr The live preview on email editing doesn't appear to be working for me. Other than that, looks good.

**Comment by petschekr** [comment]
@ehsanmasdar Weird, it works for me locally. Looks like all requests get hung up as pending to http://registration.dev.hack.gt/api/settings/email_content/*/rendered. Are there any logs?

**Comment by ehsanmasdar** [comment]
POST /api/settings/email_content/Participant-apply/rendered - - ms - -
POST /api/settings/email_content/Participant-apply/rendered - - ms - -
POST /api/settings/email_content/Chaperone-attend/rendered - - ms - -
POST /api/settings/email_content/Chaperone-attend/rendered - - ms - -
POST /api/settings/email_content/Participant-apply/rendered - - ms - -
POST /api/settings/email_content/Participant-apply/rendered - - ms - -
POST /api/settings/email_content/Participant-apply/rendered - - ms - -
and
(node:21) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 75): TypeError: Cannot read property 'replace' of undefined

**Comment by petschekr** [comment]
@ehsanmasdar Can you redeploy with 35acc2c?

**Pull request merged**
