### PR TITLE
Render registration template

### LINKED ISSUE #1: Serve the registration page
Assume you have a JSON object with the configuration for the registration page is a format similar to:
```YAML
questions:
  - type: text
    text: What's good?

  - type: select
    text: 'Dietary Restrictions:'
    options:
      - Vegan
      - Vegetarian
      - Kosher
      - Paleo
```

Use this configuration to render and cache a handlebars template that is the HTML of the registration page. Finally add a route that serves this cached page.

### PR DESCRIPTION
**Pull request by ganhari123**
Closes #1

### CODE REVIEW

**Comment by ganhari123** [comment]
I added more dummy commits and pushed, is that ok?

**Comment by petschekr** [comment]
Sure, this is your own branch but if you want to undo those commits you can run `git reset --soft HEAD~3`. If you want to combine those into one single commit with a better title, you can then run `git commit` after doing that. After this, run `git push --force` to force push to this branch. For the future, make sure you never run a force push on a branch that only you have downloaded since it messes with the history.

**Comment by ganhari123** [comment]
ok makes sense!

Did the code for loading, rendering. and serving the template to the templates.ts file get added on the pull request?

**Comment by petschekr** [comment]
I don't think so because it's not showing up under the changes tab here

**Comment by ganhari123** [comment]
should i try to manually add everything to template.ts or should i commit more

**Comment by petschekr** [comment]
You should commit whenever a particular section of code is finished. I'm not exactly sure what you mean by manually adding it to `template.ts`.

**Comment by ganhari123** [comment]
I mean should i add the code to serve the template to template.ts, because i didnt edit that file, i changed the template.js file. earlier you mentioned that it would be automatically added if i commit some more.

**Comment by petschekr** [comment]
You should put it into the .ts file. JavaScript filles are currently ignored in the `.gitignore` because typescript compiles to JavaScript and will overwrite any changes after compiling is done by running `tsc`. Check out the README for more information on how to compile and run the server.

**Comment by ganhari123** [comment]
Hey i fixed it! I put everything in the typescript files! Let me know if thats good

**Comment by petschekr** [comment]
Accelerating this to completion

**Pull request merged**
