### PR TITLE
Load paths to config files from env vars

### LINKED ISSUE #56: Missing Favicon
This is the lowest possible priority.

Preferably make this a configurable setting etc.

### LINKED ISSUE #108: Add ability to specify custom CSS files.

### PR DESCRIPTION
**Pull request by illegalprime**
Can configure stuff like this:

```bash
THEME_FILE=/home/michael/Downloads/normalize.css \
FAVICON_FILE=/home/michael/Downloads/favicon.ico \
QUESTIONS_FILE=/home/michael/Downloads/questions.json npm run start
```

Closes #56 
Closes #108

### CODE REVIEW

**Comment by illegalprime** [comment]
Don't merge until the preview changes css background and the favicon is there.

**Comment by illegalprime** [comment]
OK this can be merged!

**Comment by petschekr** [comment]
@illegalprime Please make sure that your custom theme for https://registration-config-paths.pr.hack.gt isn't being applied to `master` before I merge this.

**Comment by illegalprime** [comment]
it isn't, `pr` configs are ephemeral, merge when ready.

**Pull request merged**
