### PR TITLE
Add three schools to HackGT 4 questions

### PR DESCRIPTION
**Pull request by AJLiu**
@ehsanmasdar

### CODE REVIEW

**Comment by petschekr** [comment]
Can you also add the University of Waterloo, University of Toronto, and Texas A&M?

**Comment by petschekr** [comment]
Also, the college question appears more than once. Make sure you've updated all instances.

**Comment by AJLiu** [comment]
Texas A&M already on there

**Comment by petschekr** [comment]
Weird, some people used the other field to put it in

**Pull request merged**
