### PR TITLE
Graphs

### PR DESCRIPTION
**Pull request by mjkaufer**
Added graphs to admin panel instead of →

Sorry for the delay, kinda forgot to push a while ago

### CODE REVIEW

**Comment by BunsenMcDubbs** [comment]
@mjkaufer can you include 1 or 2 screenshots of the functionality?

**Comment by mjkaufer** [comment]
example 1

example 2

**Comment by petschekr** [comment]
@mjkaufer Are the graphs also weirdly aligned for you in the admin panel? Also, I just rebased your changes onto the current `master` branch to tidy up the merge commit and force pushed so you'll have to `git fetch` and `git reset --hard origin/graphs` to update your copy.

screenshot_20170524_191807

**Comment by mjkaufer** [comment]
You're right – I was only testing it on my display. I just pushed some
changes that should fix formatting

**Comment by petschekr** [comment]
Hmm it looks better now but it's still getting cut off because it's not the same size as the rest of the table

**Comment by mjkaufer** [comment]
Can you send me a screenie of that? I don't see it getting cut off on my end

**Comment by petschekr** [comment]
Just fixed it in 4240c64061fa4a54710307e63e9de5fece7401f6. Can you confirm that it still works on your screen with those changes?

**Comment by mjkaufer** [comment]
Yep - looks pretty from my view

**Comment by petschekr** [comment]
Awesome, I'm merging this in now

**Pull request merged**
